data:
  input_type: half_seq
  test_split: test
  input_pointcloud_corresponding: false
  half_seq_folder: pcl_half_seq
training:
  out_dir:  out/half_test_us
test:
  model_file: /home/chang/Videos/human/occupancy_flow/ckpt/half_10.pt