data:
  input_type: depth_seq
  test_split: test_new_individual
  input_pointcloud_corresponding: false
  depth_seq_folder: depth_rotate45
training:
  out_dir:  out/partial_test_ui
test:
  model_file: /home/chang/Videos/human/occupancy_flow/ckpt/partial_57.pt